### ISSUE TITLE
deprecated macros of console_bridge in tf2/src/buffer_core.cpp

### ISSUE THREAD

**Issue by majorx234** [ros-gbp/geometry2-release#2]
console-bridge renamed its logWarn function to CONSOLE_BRIDGE_logWarn and logError to CONSOLE_BRIDGE_logError.
See [commit in cosnole_bridge](https://github.com/ros/console_bridge/pull/48/commitsl) 

possible solution:
rename these functions and add something like

```
#ifndef CONSOLE_BRIDGE_logWarn
  #define CONSOLE_BRIDGE_logWarn logWarn
#endif
#ifndef CONSOLE_BRIDGE_logError
  #define CONSOLE_BRIDGE_logError logError
#endif
```

to get backward compatiblity with libconsole-bridge-dev < 0.3.0,

**Comment by tfoote** [comment]
Please consider opening this as a PR on the source repository for further consideration. However as newer branches don't have supported platforms with the lower version of console bridge adding this backwards compatibility is not something that would be adding complexity for an unsupported platform and unlikely to be helpful for ongoing maintenance. The indigo/kinetic branch has compatible api calls with the old version.
